apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: myextranet-container
          env:
            - name: proxy_host
              value: "__YOUR_DATA__"
            - name: proxy_port
              value: "__YOUR_DATA__"

